### Get all collections
http://localhost:8080/api/collections

### Add a new collection
POST http://localhost:8080/api/collections HTTP/1.1
content-type: application/json

{
    "name": "Wunschliste für den 6. Geburtstag von Frauke"
}

### Get a collection by its ID
http://localhost:8080/api/collections/992e4141-add3-49ba-875b-d92da4ea9a18


### Post an invalid collection
POST http://localhost:8080/api/collections HTTP/1.1
content-type: application/json

{
    "name": ""
}

### Modify a collection
PUT http://localhost:8080/api/collections/992e4141-add3-49ba-875b-d92da4ea9a18 HTTP/1.1
content-type: application/json

{
    "name": "Kapitalanlagen in Leipzig"
}

### Delete a collection
DELETE http://localhost:8080/api/collections/c725efeb-de77-46df-916a-2fc195376386
